sudo: required
services:
  - docker

before_install:
  - docker build -t willweston/docker-react:test -f dev/Dockerfile .

script:
  - docker run willweston/docker-react:test npm run test -- --coverage