version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    ports: 
      - "9000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: ["npm", "run", "test"]
    volumes:
      - /app/node_modules
      - .:/app